firmware: use typing.List instead of list for type hint
list is not subscriptable in Python 3.8.

Fixes:

    File "/home/runner/work/pybricksdev/pybricksdev/pybricksdev/firmware.py", line 37, in <module>
        "mpy-cross-options": list[str],
    TypeError: 'type' object is not subscriptable