cli/flash: fix crash due to passing wrong arg to ZipFile
The refactoring done in 0dd78369 contained a mistake and passes the
wrong argument to ZipFile() which leads to the following crash:

    Traceback (most recent call last):
    File "/home/laurens/git-pybricks/pybricks-micropython/.venv/bin/pybricksdev", line 8, in <module>
        sys.exit(main())
    File "/home/laurens/git-pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/pybricksdev/cli/__init__.py", line 374, in main
        asyncio.run(subparsers.choices[args.tool].tool.run(args))
    File "/home/laurens/.pyenv/versions/3.8.2/lib/python3.8/asyncio/runners.py", line 43, in run
        return loop.run_until_complete(main)
    File "/home/laurens/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
    File "/home/laurens/git-pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/pybricksdev/cli/flash.py", line 309, in flash_firmware
        archive = zipfile.ZipFile(firmware)
    File "/home/laurens/.pyenv/versions/3.8.2/lib/python3.8/zipfile.py", line 1269, in __init__
        self._RealGetContents()
    File "/home/laurens/.pyenv/versions/3.8.2/lib/python3.8/zipfile.py", line 1332, in _RealGetContents
        endrec = _EndRecData(fp)
    File "/home/laurens/.pyenv/versions/3.8.2/lib/python3.8/zipfile.py", line 264, in _EndRecData
        fpin.seek(0, 2)
    AttributeError: 'bytearray' object has no attribute 'seek'

Fixes: https://github.com/pybricks/support/issues/617