tools.checksum: Fix CRC32
The name `data` was being reused for a separate value an causing a crash.

Fixes the error:

    Traceback (most recent call last):
    File "/home/david/work/pybricks/pybricksdev/.venv/bin/pybricksdev", line 5, in <module>
        main()
    File "/home/david/work/pybricks/pybricksdev/pybricksdev/cli/__init__.py", line 413, in main
        asyncio.run(subparsers.choices[args.tool].tool.run(args))
    File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
    File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
    File "/home/david/work/pybricks/pybricksdev/pybricksdev/cli/__init__.py", line 242, in run
        firmware, metadata = await create_firmware(args.firmware, args.name)
    File "/home/david/work/pybricks/pybricksdev/pybricksdev/flash.py", line 102, in create_firmware
        crc32_checksum(io.BytesIO(firmware), metadata["max-firmware-size"] - 4),
    File "/home/david/work/pybricks/pybricksdev/pybricksdev/tools/checksum.py", line 129, in crc32_checksum
        data = int.from_bytes(data[index : index + 4], "little")
    TypeError: 'int' object is not subscriptable

Also add type hints while we are touching this.